[package]
name = "kernel"
version = "0.0.1"

[lib]
crate-type = ["staticlib"]
name = "kernel"
path = "src/lib.rs"

[dependencies]
rlibc = "1.0.0"

[profile.debug]
codegen-units = 1
debug = true
debug-assertions = true
lto = false
opt-level = 0
panic = "unwind"
rpath = false
